### ISSUE TITLE
userPrefrences is undocumented

### ISSUE THREAD

**Issue by gaeoh** [lunafromthemoon/RenJS#11]
These, maybe some more are undocumented in the docs page.

**config.yaml**
```
userPreferences:
  textSpeed: 100 # More is faster, percent?
  autoSpeed: 150
  bgmv: 0.5
  sfxv: 0.1
  muted: false
```
